name: assignment
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  # flutter_localizations: 
  #   sdk: flutter
 
  
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  flutter_bloc: ^8.1.3
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  equatable: ^2.0.5
  intl: ^0.19.0
  http: ^1.2.1
  dio: ^5.1.2
  fluttertoast: ^8.0.9



flutter:

  uses-material-design: true
  assets: 
  - assets/
  - assets/images/

  fonts: 
  - family: Inter
    fonts: 
      - asset: assets/fonts/InterRegular.ttf
        weight: 400



